### ISSUE TITLE
Crear wireframes y mockups para la interfaz de creación de cuenta de investigador

### ISSUE THREAD

**Issue by nadiagutierrez89** [experiment-hub/experiment-hub-frontend#31]
Diseñar pantallas de login/registro de investigador.

Tiene que tener campos como:
- email
- nombre
- organización/universidad
- cual es el objetivo de usar la herramienta (encuestas, experimento cientifico, etc.)
- password

**Comment by juancuiule** [comment]
![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/013672c6-2bda-441f-94f2-866fbb64a61a)
