### ISSUE TITLE
Crear wireframes y mockup para la pantalla inicial de la plataforma

### ISSUE THREAD

**Issue by nadiagutierrez89** [experiment-hub/experiment-hub-frontend#32]
Crear y diseñar wireframes para la pantalla inicial de la plataforma donde el usuario debería poder ver las distintas funcionalidades. Tiene que tener un call to action para registrarse como investigador.

**Comment by juancuiule** [comment]
Llegué a este mockup inspirandome en la home de Vercel que deja claro los pasos para llegar a algo y las herramientas que da en cada paso.

![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/e9170f8c-7146-4eef-a0f7-29c22e498b16)

![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/ffa82783-de7f-425c-8cc8-c1a7eed6cb2c)



![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/785863b2-6907-48a3-b151-794b60ea6920)
