### ISSUE TITLE
Mockup de los componentes

### ISSUE THREAD

**Issue by carobaldino** [experiment-hub/experiment-hub-frontend#40]

**Comment by juancuiule** [comment]
![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/b031bc82-7a0f-4bde-be94-09ae0ded4762)
![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/9384c27b-f2f3-42db-8c77-1fb7485755dd)
![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/68e6683d-0271-479b-8d1b-0fa544080294)
![Image](https://github.com/experiment-hub/experiment-hub-frontend/assets/12143451/ff16a49b-30c8-44f1-a5c8-a2baea851692)
